package model;
// Generated 28/10/2014 02:52:49 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name="curso"
    ,catalog="proyectoingsoft"
)
public class Curso  implements java.io.Serializable {


     private int idCurso;
     private Profesor profesor;
     private Materia materia;
     private Set comentarios = new HashSet(0);
     private Set evaluacions = new HashSet(0);

    public Curso() {
    }

	
    public Curso(int idCurso, Profesor profesor, Materia materia) {
        this.idCurso = idCurso;
        this.profesor = profesor;
        this.materia = materia;
    }
    public Curso(int idCurso, Profesor profesor, Materia materia, Set comentarios, Set evaluacions) {
       this.idCurso = idCurso;
       this.profesor = profesor;
       this.materia = materia;
       this.comentarios = comentarios;
       this.evaluacions = evaluacions;
    }
   
     @Id 

    
    @Column(name="idCurso", unique=true, nullable=false)
    public int getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Profesor", nullable=false)
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Materia", nullable=false)
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="curso")
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="curso")
    public Set getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set evaluacions) {
        this.evaluacions = evaluacions;
    }




}


