package model;
// Generated 28/10/2014 02:52:49 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evaluacion generated by hbm2java
 */
@Entity
@Table(name="evaluacion"
    ,catalog="proyectoingsoft"
)
public class Evaluacion  implements java.io.Serializable {


     private int idEvaluacion;
     private Curso curso;
     private Date fecha;
     private BigDecimal calif;

    public Evaluacion() {
    }

    public Evaluacion(int idEvaluacion, Curso curso, Date fecha, BigDecimal calif) {
       this.idEvaluacion = idEvaluacion;
       this.curso = curso;
       this.fecha = fecha;
       this.calif = calif;
    }
   
     @Id 

    
    @Column(name="idEvaluacion", unique=true, nullable=false)
    public int getIdEvaluacion() {
        return this.idEvaluacion;
    }
    
    public void setIdEvaluacion(int idEvaluacion) {
        this.idEvaluacion = idEvaluacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="curso", nullable=false)
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="calif", nullable=false, precision=2, scale=1)
    public BigDecimal getCalif() {
        return this.calif;
    }
    
    public void setCalif(BigDecimal calif) {
        this.calif = calif;
    }




}


