package model;
// Generated 28/10/2014 02:52:49 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Materia generated by hbm2java
 */
@Entity
@Table(name="materia"
    ,catalog="proyectoingsoft"
    , uniqueConstraints = @UniqueConstraint(columnNames="Nombre") 
)
public class Materia  implements java.io.Serializable {


     private int idMateria;
     private String nombre;
     private Set cursos = new HashSet(0);

    public Materia() {
    }

	
    public Materia(int idMateria, String nombre) {
        this.idMateria = idMateria;
        this.nombre = nombre;
    }
    public Materia(int idMateria, String nombre, Set cursos) {
       this.idMateria = idMateria;
       this.nombre = nombre;
       this.cursos = cursos;
    }
   
     @Id 

    
    @Column(name="idMateria", unique=true, nullable=false)
    public int getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(int idMateria) {
        this.idMateria = idMateria;
    }

    
    @Column(name="Nombre", unique=true, nullable=false, length=70)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="materia")
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


