package model;
// Generated 28/10/2014 02:52:49 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Profesor generated by hbm2java
 */
@Entity
@Table(name="profesor"
    ,catalog="proyectoingsoft"
    , uniqueConstraints = @UniqueConstraint(columnNames="Nombre") 
)
public class Profesor  implements java.io.Serializable {


     private int idProfesor;
     private String nombre;
     private Set cursos = new HashSet(0);

    public Profesor() {
    }

	
    public Profesor(int idProfesor, String nombre) {
        this.idProfesor = idProfesor;
        this.nombre = nombre;
    }
    public Profesor(int idProfesor, String nombre, Set cursos) {
       this.idProfesor = idProfesor;
       this.nombre = nombre;
       this.cursos = cursos;
    }
   
     @Id 

    
    @Column(name="idProfesor", unique=true, nullable=false)
    public int getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(int idProfesor) {
        this.idProfesor = idProfesor;
    }

    
    @Column(name="Nombre", unique=true, nullable=false, length=60)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="profesor")
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


